-- /supabase/migrations/0000_initial_schema.sql

-- PROFILES TABLE
-- Stores public-facing user data.
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,

  constraint username_length check (char_length(username) >= 3)
);

-- VEHICLES TABLE
-- Stores user's vehicles, identified by registration plate.
create table vehicles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  registration_plate text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- A user should not be able to add the same vehicle twice.
  unique(user_id, registration_plate)
);

-- FINES TABLE
-- Stores details for each penalty charge notice (PCN) a user contests.
create table fines (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  vehicle_id bigint references vehicles(id) not null,
  pcn_number text not null,
  issuing_authority text not null,
  contravention_date date not null,
  generated_appeal_text text,
  status text default 'Appeal Generated' not null, -- e.g., 'Appeal Generated', 'Submitted', 'Won', 'Lost'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- Add comments to explain the schema
comment on table profiles is 'Public profile information for each user.';
comment on table vehicles is 'Stores vehicles associated with a user account.';
comment on table fines is 'Records of all penalty charge notices being contested.'; 